# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 七次方工作室
email: cqwd2010@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 七次方，永远更好的，探索网站。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://llorch-zh.github.io" # the base hostname & protocol for your site
twitter_username: null
github_username:  llorch-zh

# Build settings
markdown: kramdown
